all:
	@$(MAKE) -C src

run:
	PYTHONPATH=. python3 -m {{ py_name }}

install: all
	pip3 install --upgrade .

dist: all
	python3 -m build

clean:
	@find . -type d -name __pycache__ -exec rm -rf {} +

distclean: clean
	@rm -rf build/ dist/ *.egg-info/
